module top (
    input logic CLK,          // system clock
    input logic RST          // reset signal
);

    // instruction fields sent from datapath to controller
    logic [6:0] Op;          // instruction opcode
    logic [2:0] funct3;      // funct3 field for instruction decoding
    logic       funct7b5;    // instruction bit 30 for alu decoding

    // alu status signals sent from datapath to controller
    logic       Zero;        // alu zero flag (used for BEQ/BNE)
    logic       Negative;    // alu sign flag (used for signed branches)
    logic       Overflow;    // alu overflow flag (used for signed branches)
    logic       Carry;       // alu carry flag (used for unsigned branches)

    // control signals generated by controller
    logic [1:0] ResultSrc;   // select alu result or memory data for write-back
    logic       MemWrite;    // data memory write enable
    logic [1:0] PCSrc;       // select next PC source
    logic [2:0] ALUSrc;      // select alu operand B source
    logic       RegWrite;    // register file write enable
    logic [2:0] ImmSrc;      // immediate format selector
    logic [3:0] AlUControl;  // alu operation selector
    logic Branch_taken, Jump;

    // controller: generates control signals based on instruction opcode and alu flags
    (* DONT_TOUCH = "true" *) controller Controller(
        .Op(Op),
        .funct3(funct3),
        .funct7b5(funct7b5),
        .Zero(Zero),
        .Negative(Negative),
        .Overflow(Overflow),
        .Carry(Carry),
        .ResultSrc(ResultSrc),
        .MemWrite(MemWrite),
        .PCSrc(PCSrc),
        .Branch_taken(Branch_taken),
        .Jump(Jump),
        .ALUSrc(ALUSrc),
        .RegWrite(RegWrite),
        .ImmSrc(ImmSrc),
        .AlUControl(AlUControl)
    );


    // datapath: contains pc, instruction memory, register file, alu, immediate generator, and data memory
    (* DONT_TOUCH = "true" *) datapath Datapath(
        .CLK(CLK),
        .RST(RST),
        .PCSrcE(PCSrc),
        .RegWriteE(RegWrite),
        .ImmSrcE(ImmSrc),
        .ALUSrcE(ALUSrc),
        .AlUControlE(AlUControl),
        .MemWriteE(MemWrite),
        .ResultSrcE(ResultSrc),
        .Branch_taken(Branch_taken),
        .JumpE(Jump),
        .Op(Op),
        .funct3(funct3),
        .funct7b5(funct7b5),
        .Zero(Zero),
        .Negative(Negative),
        .Overflow(Overflow),
        .Carry(Carry)
    );
endmodule : top
